{
    "openapi": "3.0.3",
    "info":{
        "title":"Challenge API",
        "description":"Uma api que cadastra cidades e clientes",
        "license":{
            "name": "MIT",
            "url": "https://choosealicense.com/licenses/mit/"
        },
        "version": "1.0.0"
    },

    "paths":{
        "/api/v1/cities":{
            "get": {
                "description": "Retorna todas as cidades",
                "tags": [
                    "Cidades"
                ],
                "parameters": [
                    {
                        "name": "limit",
                        "in": "query",
                        "description":"limita a quantidade de resultados por pagina"
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description":"define a pagina dos resultado"
                    },
                    {
                        "name": "cidade",
                        "in": "query",
                        "description":"filtra os resultados pelo nome da cidade"
                    },
                    {
                        "name": "estado",
                        "in": "query",
                        "description":"filtra os resultados pelo nome do estado"
                    }

                ],
                "responses":{
                    "200":{
                        "description":"Ok",
                        "schema":{
                            "$ref":"#components/schemas/cidades"
                        },
                        "content": {
                            "application/json": {
                            "examples":{
                                "Lista de objetos paginados":{
                                "value":{
                                "docs": [
                                    {
                                        "id": "eee29c11-eb4f-42d4-95db-10e5d65b6d04",
                                        "cidade": "Fortaleza",
                                        "estado": "Ceara"
                                    }
                                ],
                                "limit": 10,
                                "page": 1,
                                "pages": 1,
                                "totalDocs": 1
                            }
                        }
                        }
                        }
                        }      
                    },
                    "404":{
                        "description":"NotFound",
                        "content": {
                            "application/json":{
                    
                        "examples":{
                            "Erro de não encontrado":{
                                "value":{
                                    "description": "Notfound",
                                    "message": "No results found"
                                }
                            }    
                        }
                    }
                    }
                },
                    "400":{
                        "description":"Bad Request",
                        "content":{
                            "application/json":{

                                "examples":{
                                    "Erro de validação de queries":{
                                        "value":[
                                            {
                                                "description": "qualquercoisa",
                                                "message": "\"qualquercoisa\" is not allowed"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }

                }
            },
            "post":{
                "description":"Cadastra uma nova cidade",
                "tags": [
                    "Cidades"
                ],
                "requestBody":{
                    "content":{
                        "application/json":{
                            "schema":{
                                "$ref":"#components/schemas/cidades"
                            },
                            "examples":{
                                "cidade":{
                                    "value":{
                                        "cidade":"Florianopolis",
                                        "estado":"Santa Catarina"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "201":{
                        "description":"Created",
                        "content":{
                            "application/json":{
                                "schema":{
                                    "$ref":"#components/schemas/cidades"
                                },
                                "examples":{
                                    "Nova Cidade Cadastrada com sucesso":{
                                        "value":{
                                            "cidade": "Florianopolis",
                                            "estado": "Santa Catarina",
                                            "id": "d9267217-310e-4fd0-ab31-2db4dc148029"
                                        }
                                }   }
                            }
                        }
                    },
                    "400":{
                        "description":"Bad Request",
                        "content":{
                            "application/json":{
                                "examples":{
                                    "Cadastrar uma cidade com o mesmo nome e estado":{
                                        "value":{
                                            "description": "BadRequest",
                                            "message": "City already exists"
                                        }
                                    },
                                    "Body incompleto ou com conteudo que nao pertence a tabela":{
                                        "value":[
                                            {
                                                "description": "estado",
                                                "message": "\"estado\" is required"
                                            },
                                            {
                                                "description": "qualquercoisa",
                                                "message": "\"qualquercoisa\" is not allowed"
                                            }
                                        ]

                                    }
                                }
                            }
                        }
                    }
                }

            }
        },
        "/api/v1/cities/{city}":{
            "get":{
                "description":"Lista todas as cidades por nome",
                "tags":[
                    "Cidades"
                ],
                "parameters":[
                    {
                        "name":"city",
                        "in":"path",
                        "description":"filtra os resultados pelo nome da cidade",
                        "required": true
                    }
                ],
                "responses":{
                    "200":{
                        "description":"Ok",
                        "content":{
                            "application/json":{
                                "examples":{
                                    "Cidades filtradas com paginação":{
                                        "value":{
                                            "docs": [
                                                {
                                                    "id": "d4c8419b-c05a-4a6a-bd19-0d89511d0568",
                                                    "cidade": "Bom Jesus",
                                                    "estado": "Paraiba"
                                                },
                                                {
                                                    "id": "cff6c713-2f2f-406b-8ccd-4dd5f91ca89e",
                                                    "cidade": "Bom Jesus",
                                                    "estado": "Rio Grande do Sul"
                                                },
                                                {
                                                    "id": "c9d0edbc-3804-4dcb-8964-1565d26fb78f",
                                                    "cidade": "Bom Jesus",
                                                    "estado": "Santa Catarina"
                                                }
                                            ],
                                            "limit": 10,
                                            "page": 1,
                                            "pages": 1,
                                            "totalDocs": 3
                                        }
                                    }
                                }
 
                            }
                        }
                    },
                    "404":{
                        "description":"NotFound",
                        "content": {
                            "application/json":{
                    
                        "examples":{
                            "Erro de cidades não encontradas":{
                                "value":{
                                    "description": "Notfound",
                                    "message": "No results found"
                                }
                            }    
                        }
                    }
                    }
                }
                }

            }
        },
        "/api/v1/cities/state/{state}":{
            "get":{
                "description":"Lista todas as cidades de um estado por nome",
                "tags":[
                    "Cidades"
                ],
                "parameters":[
                    {
                        "name":"state",
                        "in":"path",
                        "description":"filtra os resultados pelo nome do estado",
                        "required": true
                    }
                ],
                "responses":{
                    "200":{
                        "description":"Ok",
                        "content":{
                            "application/json":{
                                "examples":{
                                    "Cidades filtradas por estado com paginação":{
                                        "value":{
                                            "docs": [
                                                {
                                                    "id": "eee29c11-eb4f-42d4-95db-10e5d65b6d04",
                                                    "cidade": "Fortaleza",
                                                    "estado": "Ceara"
                                                },
                                                {
                                                    "id": "4bc5c364-4d13-4b97-a343-83f8f2a32012",
                                                    "cidade": "Maracanau",
                                                    "estado": "Ceara"
                                                },
                                                {
                                                    "id": "478958ae-a94d-40d9-8f19-7aa2aba3e1a8",
                                                    "cidade": "Russas",
                                                    "estado": "Ceara"
                                                }
                                            ],
                                            "limit": 10,
                                            "page": 1,
                                            "pages": 1,
                                            "totalDocs": 3
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404":{
                        "description":"NotFound",
                        "content": {
                            "application/json":{
                    
                        "examples":{
                            "Erro de cidades não encontradas":{
                                "value":{
                                    "description": "Notfound",
                                    "message": "No results found"
                                }
                            }    
                        }
                    }
                    }
                }
            }
            
            }
        }
    },
    "components": {
        "schemas": {
          "cidades": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "cidade": {
                "type": "string"
              },
              "estado": {
                "type": "string"
              }
            }
          }
    }
}
}